# -*- coding: utf-8 -*-
"""College data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vedscpmG4mxZpiH2St9JexueF9QlF15z

# College data anaylsis and visualization
"""

import pandas as pd;

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/College.csv')

df.head()

df.describe()

df.rename(columns = {'University name':'University'}, inplace=True)

df.head(2)

df.columns

import seaborn as sns

sns.scatterplot('Apps','Accept',data=df)

sns.scatterplot('PhD','Grad.Rate',data=df)

len(df[df.Private=='Yes'])

df['elite'] = df.Top10perc > 50

df.head(5)

df.groupby('elite')['University'].count()

import matplotlib.pyplot as plt
sns.countplot(df['elite'],hue=df['elite'])
plt.show()

df.loc[:,df.columns!='elite'].head(1)

sns.pairplot(df.loc[:,['Apps','Accept']])

"""*Reference - https://www.nbshare.io/notebook/224599533/How-to-Analyze-the-CSV-data-in-Pandas/*"""